config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users
  resources :songs
  resources :playlists

  get 'songs/showresult/:spotify_id' => 'songs#show_result', :as =>'show_result'
  post 'songs/showresult/:spotify_id' => 'songs#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  get '/auth/spotify/:callback' => 'users#spotify'
  post '/auth/spotify/:callback/:id' => 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  belongs_to :user, :optional => true
end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :playlists

  
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
validates :username, :presence => true, :uniqueness => true
has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :spotify_credentials, :fetch_user

private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end
# spotify credentials allow the user to search songs in the spotify database
  def spotify_credentials
    RSpotify.authenticate(Rails.application.secrets.spotify_client_id, Rails.application.secrets.spotify_client_secret)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :check_for_login
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find params[:id]
  end

  def create
    playlist = Playlist.create playlist_params
    redirect_to playlist
  end

  def edit
    @playlist = Playlist.find params[:id]

  end

  def update
    playlist = Playlist.find params[:id]
    playlist.update playlist_params
    redirect_to playlist
  end

  def destroy
    playlist = Playlist.find params[:id]
    playlist.destroy
    redirect_to playlists_path
  end

  private
  def playlist_params
    params.require(:playlist).permit(:title, :user_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :username => params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :check_for_login
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
    @song_title = params[:title]
    if @song_title.present?
      @spotify_search = RSpotify::Track.search(@song_title, limit: 50)
    end
  end

  def show_result
    @song = Song.new
    @playlist = Playlist.all
    @search_result = RSpotify::Track.find("#{ params[:spotify_id] }")

  end

  def show
    @song = Song.find params[:id]
  end

  def edit
    @song = Song.find params[:id]
  end

  def update
    song = Song.find params[:id]
    song.update song_params
    redirect_to song
  end

  def create
    song = Song.create song_params
    playlist = Playlist.find params[:playlist_id]
    playlist.songs << song
    redirect_to song
  end

  def destroy
    song = Song.find params[:id]
    song.destroy
    redirect_to songs_path
  end

private
  def song_params
    params.require(:song).permit(:title, :artist, :album, :spotify_song_id, :image, playlist_ids:[])
  end
  def playlist_params
    params.require(:playlist).permit(:playlist_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save # If it can save it it will save the user id into the session params
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def updated
    user = User.find params[:id]
    user.update user_params
    redirect_to user
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to root_path
  end

# This action aunthenticates the user with Spotify.
  def spotify
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :user_info, :display_name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container">
      <nav>
        <ul class="nav nav-tabs">
          <li class="nav-item"><%= link_to 'Home', root_path, :class => "nav-link active" %></li>
          <li class="nav-item">
              <%= link_to "Songs", songs_path, :class => "nav-link active" %>
          </li>
          <li class="nav-item">
              <%= link_to "Search Songs", new_song_path, :class => "nav-link active" %>
          </li>
          <li class="nav-item">
              <%= link_to "Playlists", playlists_path, :class => "nav-link active" %>
          </li>
          <li class="nav-item">
              <%= link_to "New playlist", new_playlist_path, :class => "nav-link active" %>
          </li>
          <% if @current_user.present? %>
          <li class="nav-item">
            <%= link_to "Log out #{ @current_user.email }", login_path, :method => 'delete', :class => "nav-link active" %>
          </li>
          <% else %>
          <li class="nav-item"><%= link_to 'Sign up', new_user_path, :class => "nav-link active" %></li>
          <li class="nav-item"><%= link_to 'Sign in', login_path, :class => "nav-link active" %></li>
          <% end %>
        </ul>


        <!-- <% if @spotify_user.present? %>
          <%= link_to "Log out #{ @spotify_user.display_name }", "/auth/spotify", :method => 'delete' %>
        <% else %>
          <%= link_to 'Sign in with Spotify', "/auth/spotify" %>
        <% end %>
          Sign in to spotify user account
      -->

      </nav>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Spotify Playlist Maker</h1>

app/views/playlists/edit.html.erb
<h1><%= @playlist.title %></h1>

<div class="row">
  <div class="col-md-4 offset-md-3">
    <%= form_for @playlist do |f| %>
      <div class="form-group">
        <%= f.label :title, :value => "#{ @playlist.title }" %>
        <%= f.text_field :title, :class => "form-control" %>
      </div>
      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>

<% @playlists.each do |playlist| %>
  <!-- this conditional will only show playlists created by the user -->
  <% if playlist.user_id == session[:user_id] %>
  <ul>
    <li><%= link_to playlist.title, playlist %></li>
  </ul>
  <% end %>
<% end %>

app/views/playlists/new.html.erb
<h1>Create a new Playlist!</h1>

<div class="row">
  <div class="col-md-4">
    <%= form_for @playlist do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
      <!-- This will assign the playlist to the current user -->
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/playlists/show.html.erb
<h1><%= @playlist.title %></h1>


    <% @playlist.songs.each do |song| %>
    <div class="row">
      <div class="col-md-4 offset-md-4">
      <ul style="list-style-type: none">
        <%=link_to image_tag(song.image, :class =>'thumb'), song %>
        <li><%= "#{ song.title } - #{ song.artist }" %></li>
      </ul>
    </div>
  </div>
    <% end %>


<div class="controls">
  <%= link_to "Rename Playlist", edit_playlist_path(@playlist) %>
  <%= button_to 'Delete Playlist', @playlist, :method => 'delete' %>
</div>

app/views/session/new.html.erb
<h1>Log In</h1>

<div class="row">
  <div class="col-md-4 offset-md-3">
    <%= form_tag login_path do%>
      <div class="form-group">
        <%= label_tag :username %>
        <%= text_field_tag :username, nil, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => "form-control" %>
      </div>

      <%= submit_tag "Sign in" %>
    <% end %>
  </div>
</div>

app/views/songs/edit.html.erb
<h1><%= @song.title %></h1>

<br>

<div class="row">
  <div class="col-md-4 offset-md-3">
    <%= image_tag @song.image, :class => 'feature' %>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= form_for @song do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :value => "#{ @song.title }", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :artist %>
      <%= f.text_field :artist, :value => "#{@song.artist}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :album %>
      <%= f.text_field :album, :value => "#{@song.album}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.url_field :image, :value => "#{@song.image}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :playlist_id %>
      <%= collection_check_boxes :song, :playlist_ids, Playlist.where(user_id: session[:user_id]), :id, :title, :class => "form-control" do |b| %>
        <%= b.check_box %>
        <%= b.label %>
      <% end %>
      <!-- The collection boxes allow the user to add that song to diferent playlists %> -->
    </div>

      <%= f.submit "Save" %>

    <% end %>
  </div>
</div>

app/views/songs/index.html.erb
<h1>All songs</h1>

<div class="row">
  <div class="col-md-4 offset-md-4">
    <% @songs.each do |song| %>
      <%= link_to image_tag(song.image, :class => 'feature'), song %>
      <ul style="list-style-type: none">
        <li><%= link_to "#{song.title} - #{song.artist}", song %></li>
      </ul>

    <% end %>

  </div>

</div>

app/views/songs/new.html.erb
<h1>Search for songs!</h1>

<div class="row">
  <div class="col-md-4">
    <!-- This form will action a GET request to get the songs from spotify -->
    <form action="<%= new_song_path %>" method='get'>
      <div class="form-group">
        <label for="">
          Title:
          <input type="text" name='title' requiered>
        </label>
      </div>
      <button>Search</button>
    </form>
  </div>
</div>
</br>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <!-- The following block of code will show the results of the search -->
    <% if @song_title.present? %> <!-- The conditional will hide the "results" when there's nothing to show -->
      <% @spotify_search.each do |result| %>
        <ul style="list-style-type: none">
          <li>
            <%= image_tag result.album.images.first['url'], :class => 'thumb' %>
            <%= link_to "#{ result.name } - #{ result.artists.first.name }", "showresult/#{ result.id }" %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<div class="row">
  <div class="col-md-4 offset-md-4">
    <%= image_tag @song.image, :class => 'feature' %>

    <ul style="list-style-type: none">
      <li>Title: <%= @song.title %></li>
      <li>Artist: <%= @song.artist %></li>
      <li>Album: <%= @song.album %></li>
      <li>
        Playlists: <% @song.playlists.each do |pl| %>
                      <ul>
                        <li><%= pl.title %></li>
                      </ul>
                    <% end %>
      </li>
    </ul>

  </div>
</div>

<div class="controls">
  <%= link_to "Edit Song", edit_song_path(@song) %>
  <%= button_to 'Delete Song', @song, :method => 'delete' %>
</div>

app/views/songs/show_result.html.erb
<h1><%= @search_result.name %> - <%= @search_result.artists.first.name %></h1>

<br>

<div class="row">
  <div class="col-md-4 offset-md-3">
    <%= image_tag @search_result.album.images.first['url'], :class => 'feature' %>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-4 offset-md-4">
    <%= form_for @song do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :value => "#{@search_result.name}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :artist %>
      <%= f.text_field :artist, :value => "#{@search_result.artists.first.name}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :album %>
      <%= f.text_field :album, :value => "#{@search_result.album.name}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :spotify_song_id, "Song ID"%>
      <%= f.text_field :spotify_song_id, :value => "#{@search_result.id}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.url_field :image, :value => "#{@search_result.album.images.first['url']}", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :playlist_id %>
      <%= select_tag :playlist_id, options_for_select(Playlist.where(user_id: session[:user_id]).pluck(:title, :id)), :class => "form-control" %>
      <!-- The dropdown will show only the playlist the current user has created -->
    </div>

      <%= f.submit "Add Song" %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%=  msg %></li>
    <% end %>
  </ol>
<% end %>

<div class="row">
  <div class="col-md-4 offset-md-3">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>

      <%= f.submit "Sign up" %>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<ul>
  <li>Email: <%= @user.email %></li>
  <li>Username: <%= @user.username %></li>
  <li>User Info: <%= @user.user_info %></li>
  <li>Name: <%= @user.display_name %></li>
</ul>

<div class="controls">
  <%= button_to 'Delete User', @user, :method => 'delete' %>
</div>

app/views/users/spotify.html.erb
<h1><%= "#{@spotify_user.display_name}'s Spotify Profile" %></h1>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email, :value => @spotify_user.email %>

  <%= f.label :username %>
  <%= f.text_field :username, :value => @spotify_user.id %>

  <%= f.label :user_info %>
  <%= f.text_field :user_info, :value => @spotify_user.to_hash %>

  <%= f.label :display_name %>
  <%= f.text_field :display_name, :value => @spotify_user.display_name %>

  <%= f.submit %>
<% end %>